### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "asdf13@asdf.com",
    "password": "pass@123456"
}

### Signin user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "asdf12@asdf.com",
    "password": "pass@123456"
}

### Get the currently singed in user 
GET http://localhost:3000/auth/whoami

### Sign out
POST http://localhost:3000/auth/signout

### Find a particular user with a given ID
GET http://localhost:3000/auth/1

### Find all users with a given email
GET http://localhost:3000/auth?email=asdf@asdf.com

### Delete a user with a given ID
DELETE http://localhost:3000/auth/4

### Update a user with a given ID
PATCH http://localhost:3000/auth/4
Content-Type: application/json

{
    "password": "azertyny!1"
}
